
import React, { useState, useEffect } from 'react';
import { Flashcard, TestQuestion, TestResult, QuestionType, StudyConfig } from '../types';
import { generatePracticeTest, evaluateAnswer } from '../services/geminiService';

interface PracticeTestProps {
  cards: Flashcard[];
  onBack: () => void;
}

const PracticeTest: React.FC<PracticeTestProps> = ({ cards, onBack }) => {
  const [setup, setSetup] = useState(true);
  const [config, setConfig] = useState<StudyConfig>({
    questionTypes: ['multiple-choice', 'written'],
    itemCount: 10
  });

  const [questions, setQuestions] = useState<TestQuestion[]>([]);
  const [loading, setLoading] = useState(false);
  const [currentStep, setCurrentStep] = useState<'testing' | 'results'>('testing');
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [grading, setGrading] = useState(false);
  const [result, setResult] = useState<TestResult | null>(null);

  const toggleType = (type: QuestionType) => {
    setConfig(prev => ({
      ...prev,
      questionTypes: prev.questionTypes.includes(type) 
        ? prev.questionTypes.filter(t => t !== type) 
        : [...prev.questionTypes, type]
    }));
  };

  const startTest = async () => {
    if (config.questionTypes.length === 0) return;
    setLoading(true);
    setSetup(false);
    try {
      const q = await generatePracticeTest(cards, config.questionTypes, config.itemCount);
      setQuestions(q);
    } catch (e) {
      alert("Failed to generate test.");
      setSetup(true);
    } finally {
      setLoading(false);
    }
  };

  const submitTest = async () => {
    setGrading(true);
    let score = 0;
    const gradedAnswers = [];
    for (const q of questions) {
      const userAnswer = answers[q.id] || "No answer";
      const evaluation = await evaluateAnswer(q.question, q.correctAnswer, userAnswer);
      if (evaluation.isCorrect) score += 1;
      gradedAnswers.push({ questionId: q.id, userAnswer, isCorrect: evaluation.isCorrect, feedback: evaluation.feedback });
    }
    setResult({
      score: (score / questions.length) * 100,
      feedback: score === questions.length ? "Incredible! 100% Mastery." : "Strong effort. Check feedack below.",
      answers: gradedAnswers
    });
    setGrading(false);
    setCurrentStep('results');
  };

  if (setup) return (
    <div className="p-8 space-y-8 animate-in fade-in max-w-md mx-auto">
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-black italic text-slate-800">Test Setup</h2>
        <p className="text-slate-500 font-medium">Custom exam generated by AI.</p>
      </div>
      <div className="space-y-4">
        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Length</p>
        <div className="flex justify-between bg-slate-100 p-1 rounded-2xl">
          {[5, 10, 20].map(n => (
            <button key={n} onClick={() => setConfig({...config, itemCount: n})} className={`flex-1 py-3 rounded-xl text-xs font-black transition-all ${config.itemCount === n ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-400'}`}>
              {n} Qs
            </button>
          ))}
        </div>
        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest text-center mt-6">Types</p>
        <div className="grid grid-cols-1 gap-3">
          {(['multiple-choice', 'true-false', 'written'] as QuestionType[]).map(type => (
            <button key={type} onClick={() => toggleType(type)} className={`p-5 rounded-[1.5rem] border-2 flex items-center justify-between transition-all ${config.questionTypes.includes(type) ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-slate-100 bg-white text-slate-400'}`}>
              <span className="font-black uppercase text-xs tracking-wider">{type.replace('-', ' ')}</span>
              {config.questionTypes.includes(type) && <div className="w-5 h-5 bg-indigo-600 rounded-full flex items-center justify-center text-white text-[10px]">✓</div>}
            </button>
          ))}
        </div>
      </div>
      <button onClick={startTest} disabled={config.questionTypes.length === 0} className="w-full py-5 bg-indigo-600 text-white rounded-[2rem] font-black shadow-xl shadow-indigo-100">Generate Exam</button>
      <button onClick={onBack} className="w-full text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Cancel</button>
    </div>
  );

  if (loading) return (
    <div className="flex flex-col items-center justify-center p-20 space-y-4">
      <div className="w-12 h-12 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin mx-auto"></div>
      <p className="text-indigo-600 font-black italic animate-pulse uppercase text-xs tracking-widest">Generating Test...</p>
    </div>
  );

  if (currentStep === 'results' && result) return (
    <div className="p-6 space-y-8 animate-in fade-in duration-700 pb-20 max-w-2xl mx-auto">
      <div className={`p-10 rounded-[2.5rem] text-center space-y-2 shadow-2xl ${result.score > 70 ? 'bg-emerald-600 text-white shadow-emerald-100' : 'bg-red-600 text-white shadow-red-100'}`}>
        <p className="text-[10px] font-black uppercase tracking-[0.3em] opacity-80">FINAL SCORE</p>
        <h3 className="text-6xl font-black">{Math.round(result.score)}%</h3>
        <p className="font-bold text-sm italic">{result.feedback}</p>
      </div>
      <div className="space-y-4">
        {questions.map((q, idx) => {
          const graded = result.answers.find(a => a.questionId === q.id);
          return (
            <div key={q.id} className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm space-y-3">
              <h4 className="font-bold text-slate-800">{q.question}</h4>
              <div className={`p-4 rounded-2xl text-sm ${graded?.isCorrect ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>
                <p className="font-bold">Answered: {graded?.userAnswer}</p>
                <p className="mt-2 text-xs italic opacity-80">{graded?.feedback}</p>
              </div>
            </div>
          );
        })}
      </div>
      <button onClick={onBack} className="w-full py-5 bg-indigo-600 text-white rounded-3xl font-black shadow-xl shadow-indigo-100">Done</button>
    </div>
  );

  return (
    <div className="p-6 space-y-8 animate-in slide-in-from-bottom-10 pb-24 max-w-md mx-auto">
      {questions.map((q, idx) => (
        <div key={q.id} className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-100 space-y-6">
          <div className="flex justify-between items-center text-[10px] font-black text-indigo-400 uppercase tracking-widest">
            <span>Q{idx + 1}</span>
            <span className="bg-slate-50 px-3 py-1 rounded-full">{q.type}</span>
          </div>
          <h4 className="text-lg font-black text-slate-800 leading-snug">{q.question}</h4>
          {q.type === 'multiple-choice' || q.type === 'true-false' ? (
            <div className="grid grid-cols-1 gap-3">
              {(q.type === 'true-false' ? ['True', 'False'] : q.options)?.map(opt => (
                <button 
                  key={opt}
                  onClick={() => setAnswers({...answers, [q.id]: opt})}
                  className={`p-4 rounded-2xl text-left text-sm font-bold border-2 transition-all ${answers[q.id] === opt ? 'border-indigo-600 bg-indigo-50 text-indigo-700' : 'border-slate-100 text-slate-500 hover:border-slate-200'}`}
                >
                  {opt}
                </button>
              ))}
            </div>
          ) : (
            <textarea 
              className="w-full bg-slate-900 text-white placeholder-slate-500 border border-slate-800 rounded-2xl p-4 text-sm font-medium focus:border-indigo-500 focus:bg-slate-800 transition-all h-24 resize-none shadow-2xl"
              placeholder="Your answer..."
              value={answers[q.id] || ''}
              onChange={e => setAnswers({...answers, [q.id]: e.target.value})}
            />
          )}
        </div>
      ))}
      <div className="fixed bottom-0 left-0 right-0 p-6 bg-white/90 backdrop-blur-md border-t flex justify-center">
        <button 
          onClick={submitTest}
          disabled={grading || Object.keys(answers).length < questions.length}
          className="max-w-md w-full py-5 bg-indigo-600 text-white rounded-[2rem] font-black shadow-xl shadow-indigo-100 flex items-center justify-center space-x-3"
        >
          {grading ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <span>Submit to AI Proctor</span>}
        </button>
      </div>
    </div>
  );
};

export default PracticeTest;
